config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :thread_contents
  resources :topics
  devise_for :users

  root 'topics#index'

end

app/models/thread_content.rb
class ThreadContent < ActiveRecord::Base
	belongs_to :topic
	has_many :posts, :dependent => :destroy
end

app/controllers/thread_contents_controller.rb
class ThreadContentsController < ApplicationController
  before_action :set_thread_content, only: [:show, :edit, :update, :destroy]

  # GET /thread_contents
  # GET /thread_contents.json
  def index
    @thread_contents = ThreadContent.all
  end

  # GET /thread_contents/1
  # GET /thread_contents/1.json
  def show
  end

  # GET /thread_contents/new
  def new
    @thread_content = ThreadContent.new
  end

  # GET /thread_contents/1/edit
  def edit
  end

  # POST /thread_contents
  # POST /thread_contents.json
  def create
    @thread_content = ThreadContent.new(thread_content_params)

    respond_to do |format|
      if @thread_content.save
        format.html { redirect_to @thread_content, notice: 'Thread content was successfully created.' }
        format.json { render :show, status: :created, location: @thread_content }
      else
        format.html { render :new }
        format.json { render json: @thread_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thread_contents/1
  # PATCH/PUT /thread_contents/1.json
  def update
    respond_to do |format|
      if @thread_content.update(thread_content_params)
        format.html { redirect_to @thread_content, notice: 'Thread content was successfully updated.' }
        format.json { render :show, status: :ok, location: @thread_content }
      else
        format.html { render :edit }
        format.json { render json: @thread_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thread_contents/1
  # DELETE /thread_contents/1.json
  def destroy
    @thread_content.destroy
    respond_to do |format|
      format.html { redirect_to thread_contents_url, notice: 'Thread content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thread_content
      @thread_content = ThreadContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thread_content_params
      params.require(:thread_content).permit(:id, :content, :topic_id)
    end
end

app/helpers/thread_contents_helper.rb
module ThreadContentsHelper
end

app/views/thread_contents/_form.html.erb
<%= form_for(@thread_content) do |f| %>
  <% if @thread_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thread_content.errors.count, "error") %> prohibited this thread_content from being saved:</h2>

      <ul>
      <% @thread_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br>
    <%= f.collection_select(:topic_id,Topic.all,:id,:name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thread_contents/edit.html.erb
<h1>Editing Thread Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @thread_content %> |
<%= link_to 'Back', thread_contents_path %>

app/views/thread_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Thread Contents</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thread_contents.each do |thread_content| %>
      <tr>
        <td><%= thread_content.content %></td>
        <td><%= thread_content.topic_id %></td>
        <td><%= link_to 'Show', thread_content %></td>
        <td><%= link_to 'Edit', edit_thread_content_path(thread_content) %></td>
        <td><%= link_to 'Destroy', thread_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thread content', new_thread_content_path %>

app/views/thread_contents/new.html.erb
<% if cannot? :create , ThreadContent %>
	<span class="permission-message">You aren't allowed to create new thread.</span>
<% else %>
	<h1>New Thread Content</h1>

	<%= render 'form' %>

	<%= link_to 'Back', thread_contents_path %>
<% end %>

app/views/thread_contents/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <p style="font-size:20px"> <b><%= @thread_content.content %></b> 
  	<%= link_to 'add post', new_post_path if can? :create, Post %></p>
</div>

<% if cannot? :create , Post %>

<% else %>
	<p>
	<%= link_to 'Edit', edit_thread_content_path(@thread_content) if can? :edit, Post %>
	<%= link_to 'Back', topics_path %>
	<p>
<% end %>

<%= @thread_content.posts.each do |post| %>
   <p style="font-size:14px"> <b><%= post.content %></b></p>
<% end %>