config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :thread_contents
  resources :topics
  devise_for :users

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :thread_contents, :dependent => :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to programmer's forum</h1>

<div>
    <% @topics.each do |topic| %>
        <h2>
        	<%= topic.name %>:<%= topic.description %>   
        </h2> 
        <p>
        	<%= link_to 'Show', topic %>    
         	<%= link_to 'Edit', edit_topic_path(topic) if can? :edit, User %>
        	<%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, User %>
   		</p>

        <% topic.thread_contents.each do |tc|%>
          <p style="font-size:14px"> <%= link_to tc.content, tc %>  <b><%= tc.count_of_posts %> posts</b></p>
        <% end %>

    <% end %>
</div>
<br>

<%= link_to 'New Topic', new_topic_path if can? :create, User %>

app/views/topics/new.html.erb
<% if cannot? :create , Topic %>
  <span class="permission-message">You aren't allowed to create new topic.</span>
<% else %>

	<h1>New Topic</h1>

	<%= render 'form' %>

	<%= link_to 'Back', topics_path %>
<% end %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>
<% if cannot? :create , Post %>

<% else %>
	<%= link_to 'Edit', edit_topic_path(@topic) %> |
	<%= link_to 'Back', topics_path %>
<% end %>